### ISSUE TITLE
Add options to start a deployed flow

### ISSUE THREAD

**Issue by AlvinCJin** [hermannpencole/nifi-config#19]
Hello,

Is it possible to add a feature to start a flow and its controller service after deployment?
That would be very helpful and avoid calling the rest api separately.

Thanks.

**Comment by hermannpencole** [comment]
I do not fully understand what you need
You can use this option
-noStartProcessors   for     turn off auto start of the processors after update of the config

**Comment by AlvinCJin** [comment]
Thanks for clarification.
I didn't notice that the flow is auto-started by using the Updateconfig mode.
