### ISSUE TITLE
Cant Work with publish Kafka processor (nifi 1.4)

### ISSUE THREAD

**Issue by externus** [hermannpencole/nifi-config#29]
Hi,
when Im using the publishKafka Processor (0.10 or 0.11) in my template, than the tool stucks after "communicate with nifi 1.4.0" message.
I cant undeploy the template when this processor is in my group and also I cant updateConfig with this processor in my group.
Pls resolve the problem.

thx

**Comment by hermannpencole** [comment]
Hi,
I need more details to investigate ;
Can you send the logs please ?
(And if you can, can you give me the sample ?)

thanks,

**Comment by externus** [comment]
Hi,
where can I find the log?
Here is the template:

[prototype1.zip](https://github.com/hermannpencole/nifi-config/files/1527985/prototype1.zip)

**Comment by hermannpencole** [comment]
Thanks 👍 ,
There was a bug : nifi-config started the processors before to configure them instead of stopping them.
I did release 1.1.17 that fixes this bug.
I am really sorry for any inconvenience caused!

**Comment by externus** [comment]
Hi,
thx for the fast fix.
Tried the new version and it seems working properly.
