### ISSUE TITLE
Nifi 1.3.0 Extract/UpdateConfig - Full and brokes relationship

### ISSUE THREAD

**Issue by gitfirenz** [hermannpencole/nifi-config#3]
I'm on the brand new NIFI 1.3.0

I have two issues : 
1/ ExtractConfig extracts the full config, of all my processors groups, not the one specified in the branch
2/ UpdateConfig brokes all output relationships (no issues on log)

**Comment by hermannpencole** [comment]
Hi,
1/ If i unsterstand ; Today, the extractConfig mode is recursive, and you need to extract your configuration without recursive mode ? can you open a new issue for this (In the meantime you can manually remove the attribute "groupProcessorsEntity"  from the configuration file.) 
2/ Yes, i reproduce it, the autoTerminatedRelationships is deleted, i will correct it today.
Thanks

**Comment by gitfirenz** [comment]
Thanks. I will open another issue for the 1st one.

**Comment by hermannp** [comment]
nifi-deploy-config is release in 1.1.3.
If is it ok for you can you close this issue ?

**Comment by hermannpencole** [comment]
nifi-deploy-config is release in 1.1.3.
If is it ok for you can you close this issue ?
