### ISSUE TITLE
nifi-config undeploy fails on stopping processors

### ISSUE THREAD

**Issue by luzhanov** [hermannpencole/nifi-config#30]
For some of our configurations we've faced the next issue: 

1. We have a processor which creates multiple connections (as multiple parallel threads) and these connections are long running (i.e. high-latency source)
2. When we are running nifi-config in undeploy mode then `ProcessorService#setStop` method executes successfully telling that processor X is `STOPPED`
3. Few steps later on group deletion we got an ApiException telling us "Conflict: X is running"

After deeper investigation I came to conclusion that it might be a NiFi API issue - `processorsApi#updateProcessor` returns `STOPPED `state while processor's threads are still running.

**Comment by hermannpencole** [comment]
In version 1.1.18, nif-config expects 0 ActiveThreadCount to mark a processor as stopped.
I do not see any change. tell me if it's ok for you
Thanks

**Comment by luzhanov** [comment]
I've tested the latest version and everything works fine. I think we can close this issue.
Thank you for solving this!
