### ISSUE TITLE
Nifi 1.3.0 ExtractConfig - Full

### ISSUE THREAD

**Issue by gitfirenz** [hermannpencole/nifi-config#4]
With Nifi 1.3.0.

Here is my "flow view" :
Nifi
**Nifi/DEV/MF70
Nifi/DEV/MF70/ErrorsManagement**
Nifi/DEV/MF76
Nifi/PROD/MF70
Nifi/PROD/MF70/ErrorsManagement
Nifi/PROD/MF76
Nifi/DEV/Sandbox

When i use "extractConfig" with branch "**Nifi/DEV/MF70**", i get the full flow view, not only MF70 and MF70/ErrorsManagement.

(My goal is to extract from Nifi/DEV/MF70, keep and update the usefull value, and inject to Nifi/PROD/MF70)

**Comment by hermannpencole** [comment]
Ok i see the problem you must use this option -branch "root>DEV>MF70".
I will improve the logs and throw an error if the first level is not root

**Comment by hermannp** [comment]
nifi-deploy-config is release in 1.1.3.
If is it ok for you can you close this issue ?

**Comment by hermannpencole** [comment]
nifi-deploy-config is release in 1.1.3.
If is it ok for you can you close this issue ?

**Comment by gitfirenz** [comment]
I'll check this tomorow morning. Thanks !

**Comment by gitfirenz** [comment]
This one is ok, thanks !
